qualities:
  major:
    intervals: [0, 4, 7]
  minor:
    intervals: [0, 3, 7]
  diminished:
    intervals: [0, 3, 6]
  augmented:
    intervals: [0, 4, 8]

extensions:
  triad:
    additional_intervals: []
  seventh:
    additional_intervals: [10]
    enabled: false
  major_seventh:
    additional_intervals: [11]
    enabled: false
