qualities:
  major:
    intervals: [0, 4, 7]
  minor:
    intervals: [0, 3, 7]
  diminished:
    intervals: [0, 3, 6]
  augmented:
    intervals: [0, 4, 8]

extensions:
  triad:
    members: 3
  seventh:
    members: 4
    enabled: false
  ninth:
    members: 5
    enabled: false
  eleventh:
    members: 6
    enabled: false
  flat_ninth:
    members: 5
    alterations: {4: -1}
    enabled: false
  sharp_eleventh:
    members: 6
    alterations: {5: 1}
    enabled: false
