TEMPO = 120
MIN_TEMPO = 32
MAX_TEMPO = 1024

GROUPS = 1
MIN_GROUPS = 1
MAX_GROUPS = 4

MEASURES = 2
MIN_MEASURES = 1
MAX_MEASURES = 8

TIME_SIGNATURE_NUMERATOR = 4
MIN_TIME_SIGNATURE_NUMERATOR = 1
MAX_TIME_SIGNATURE_NUMERATOR = 32

TIME_SIGNATURE_DENOMINATOR = 4
MIN_TIME_SIGNATURE_DENOMINATOR = 1
MAX_TIME_SIGNATURE_DENOMINATOR = 32
