lowest_note: 40
highest_note: 90
intervals_definitions:
    prime: 0
    minor second: 1
    major second: 2
    minor third: 3
    major third: 4
    perfect fourth: 5
    tritone: 6
    perfect fifth: 7
    minor sixth: 8
    major sixth: 9
    minor seventh: 10
    major seventh: 11
    octave: 12
    minor ninth: 13
    major ninth: 14
    minor tenth: 15
    major tenth: 16
    perfect eleventh: 17
    octave and tritone: 18
    perfect twelfth: 19
    minor thirteenth: 20
    major thirteenth: 21
    minor fourteenth: 22
    major fourteenth: 23
    double octave: 24

