lowest_note: 40
highest_note: 90
intervals_definitions:
    'prime': 0
    'minor second': 1
    'major second': 2
    'minor third': 3
    'major third': 4
    'perfect fourth': 5
    'tritone': 6
    'perfect fifth': 7
    'minor sixth': 8
    'major sixth': 9
    'minor seventh': 10
    'major seventh': 11
    'octave': 12
