lowest_note: 40
highest_note: 90
chords_definitions:
    '': [0, 4, 7]
    'm': [0, 3, 7]
    'dim': [0, 3, 6]
    'aug': [0, 4, 8]
    'sus4': [0, 5, 7]
    '7': [0, 4, 7, 10]
    'maj7': [0, 4, 7, 11]
    'm7': [0, 3, 7, 10]
    'm(maj7)': [0, 3, 7, 11]
