from pathlib import Path
from typing import Final

PACKAGE_DIRECTORY: Final[Path] = Path(__file__).resolve().parent
ROOT_DIRECTORY: Final[Path] = PACKAGE_DIRECTORY.parent

CONFIGS_DIRECTORY: Final[Path] = PACKAGE_DIRECTORY / "configs"
MODEL_CONFIG_DIRECTORY: Final[Path] = CONFIGS_DIRECTORY / "model"
CONDITIONING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "conditioning" / "conditioning.yml"
N_GRAM_ANALYSIS_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "analysis" / "n_grams.yml"
CHORD_VOCABULARY_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "chords.yml"
CHORD_DECODING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "chord_decoding.yml"
CHORD_FIT_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "chord_fit.yml"
REGISTER_CURVE_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "register_curve.yml"
ACCENT_FIELD_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "accent_field.yml"
HAND_COUPLING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "hand_coupling.yml"
CALIBRATION_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "generation" / "calibration.yml"
GENERATION_EVALUATION_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "evaluation" / "generation.yml"
INGESTION_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "training" / "ingestion.yml"
PROCESSING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "data" / "processing.yml"
SEGMENTATION_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "data" / "segmentation.yml"
TOKENIZATION_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "tokens" / "tokenization.yml"
PRETRAINING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "training" / "pretraining.yml"
FINETUNING_CONFIG_PATH: Final[Path] = CONFIGS_DIRECTORY / "training" / "finetuning.yml"

DEFAULT_DATA_DIRECTORY: Final[Path] = ROOT_DIRECTORY / "data"
ARTIFACTS_DIRECTORY: Final[Path] = ROOT_DIRECTORY / "artifacts"
DEFAULT_ANALYSIS_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "analysis"
DEFAULT_DIAGNOSTIC_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "diagnostics"
DEFAULT_MLFLOW_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "mlflow"
DEFAULT_MLFLOW_DB_PATH: Final[Path] = DEFAULT_MLFLOW_DIRECTORY / "mlflow.db"
DEFAULT_PROCESSED_ROOT: Final[Path] = ARTIFACTS_DIRECTORY / "processed"
DEFAULT_PROFILE_OUTPUT_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "profiles"
DEFAULT_PROCESSING_PROFILE_OUTPUT_DIRECTORY: Final[Path] = DEFAULT_PROFILE_OUTPUT_DIRECTORY / "processing"
DEFAULT_PARSING_PROFILE_OUTPUT_DIRECTORY: Final[Path] = DEFAULT_PROCESSING_PROFILE_OUTPUT_DIRECTORY / "parse"
DEFAULT_TOKENIZATION_PROFILE_OUTPUT_DIRECTORY: Final[Path] = DEFAULT_PROCESSING_PROFILE_OUTPUT_DIRECTORY / "tokenize"
DEFAULT_COMBINED_PROCESSING_PROFILE_OUTPUT_DIRECTORY: Final[Path] = (
    DEFAULT_PROCESSING_PROFILE_OUTPUT_DIRECTORY / "process"
)
DEFAULT_CHECKPOINT_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "checkpoints"
DEFAULT_PRETRAINING_CHECKPOINT_DIRECTORY: Final[Path] = DEFAULT_CHECKPOINT_DIRECTORY / "pretraining"
DEFAULT_FINETUNING_CHECKPOINT_DIRECTORY: Final[Path] = DEFAULT_CHECKPOINT_DIRECTORY / "finetuning"
DEFAULT_TRAINING_FIGURE_DIRECTORY: Final[Path] = ARTIFACTS_DIRECTORY / "figure-splits"
